Vagrant.configure('2') do |config|
  # Basic kali box
  config.vm.define 'kali', primary: true do |v|
    v.vm.box = 'kalilinux/rolling'
    v.vm.hostname = 'kali'
    v.vm.network 'private_network',
                 ip: IP_ADDRESSES[v.vm.hostname],
                 libvirt__dhcp_enabled: false
    v.vm.synced_folder '.', '/vagrant', type: 'rsync'
  end
end
