Vagrant.configure('2') do |config|
  # Basic 1604 box
  config.vm.define 'ubuntu1604', primary: true do |v|
    v.vm.box = 'generic/ubuntu1604'
    v.vm.provision 'shell', path: 'scripts/ubuntu/ubuntu_default.sh'
    v.vm.hostname = 'ubuntu1604'
    v.vm.network 'private_network',
                 ip: IP_ADDRESSES[v.vm.hostname],
                 libvirt__dhcp_enabled: false
    v.vm.synced_folder '.', '/vagrant', type: 'rsync'
  end
  # 1604 with apache test rig
  config.vm.define 'ubuntu1604-apache', primary: true do |v|
    v.vm.box = 'generic/ubuntu1604'
    v.vm.provision 'shell', path: 'scripts/ubuntu/ubuntu_default.sh'
    v.vm.provision 'shell', path: 'scripts/ubuntu/ubuntu_apache.sh'
    v.vm.hostname = 'ubuntu1604-apache'
    v.vm.network 'private_network',
                 ip: IP_ADDRESSES[v.vm.hostname],
                 libvirt__dhcp_enabled: false
    v.vm.synced_folder '.', '/vagrant', type: 'rsync'
  end
end
