Vagrant.configure('2') do |config|
  # Basic archlinux box
  config.vm.define 'arch' do |v|
    v.vm.box = 'archlinux/archlinux'
    v.vm.provision 'shell', path: 'scripts/arch/arch_default.sh'
    v.vm.hostname = 'arch'
    v.vm.network 'private_network',
                 ip: IP_ADDRESSES[v.vm.hostname],
                 libvirt__dhcp_enabled: false
    v.vm.synced_folder '.', '/vagrant', type: 'nfs', nfs_version: 3
  end

  # Arch with openconnect
  config.vm.define 'arch-openconnect' do |v|
    v.vm.box = 'archlinux/archlinux'
    v.vm.provision 'shell', path: 'scripts/arch/arch_default.sh'
    v.vm.provision 'shell', path: 'scripts/arch/arch_openconnect.sh'
    v.vm.hostname = 'arch-openconnect'
    v.vm.network 'private_network',
                 ip: IP_ADDRESSES[v.vm.hostname],
                 libvirt__dhcp_enabled: false
    v.vm.synced_folder '.', '/vagrant', type: 'nfs', nfs_version: 3
  end
end
