Vagrant.configure('2') do |config|
  # Basic ppc64le RHEL box
  config.vm.define 'ppc64le-rhel76' do |v|
    v.vm.box = 'ppc64le/rhel76'
    v.vm.provision 'shell', path: 'scripts/rhel_default.sh'
    v.vm.hostname = 'ppc64le-rhel76'
    v.vm.network 'private_network',
                 ip: IP_ADDRESSES[v.vm.hostname],
                 libvirt__dhcp_enabled: false
    v.vm.synced_folder '.', '/vagrant', type: 'nfs', nfs_version: 3

    v.vm.provider :libvirt do |libvirt|
      libvirt.driver = 'qemu'
      libvirt.machine_type = 'powernv9'
      libvirt.machine_arch = 'ppc64'
      libvirt.cpu_mode = 'custom'
      libvirt.cpu_model = ''
      libvirt.memory = '1024'
      libvirt.graphics_type = 'none'
      libvirt.emulator_path = '/usr/bin/qemu-system-ppc64'
    end
  end
end
