Vagrant.configure('2') do |config|
  # Basic 2204 box
  config.vm.define 'ubuntu2204', primary: true do |v|
    v.vm.box = 'generic/ubuntu2204'
    v.vm.provision 'shell', path: 'scripts/ubuntu/ubuntu_default.sh'
    v.vm.hostname = 'ubuntu2204'
    v.vm.network 'private_network',
                 ip: IP_ADDRESSES[v.vm.hostname],
                 libvirt__dhcp_enabled: false
    v.vm.synced_folder '.', '/vagrant', type: 'rsync'
  end
end
