Vagrant.configure('2') do |config|
  # Basic 20.04 box
  config.vm.define 'ubuntu2004', primary: true do |v|
    v.vm.box = 'generic/ubuntu2004'
    v.vm.provision 'shell', path: 'scripts/ubuntu/ubuntu_default.sh'
    v.vm.hostname = 'ubuntu2004'
    v.vm.network 'private_network',
                 ip: IP_ADDRESSES[v.vm.hostname],
                 libvirt__dhcp_enabled: false
    v.vm.synced_folder '.', '/vagrant', type: 'rsync'
  end

  # 20.04 with apache test rig
  config.vm.define 'ubuntu2004-apache' do |v|
    v.vm.box = 'generic/ubuntu2004'
    v.vm.provision 'shell', path: 'scripts/ubuntu/ubuntu_default.sh'
    v.vm.provision 'shell', path: 'scripts/ubuntu/ubuntu_apache.sh'
    v.vm.hostname = 'ubuntu2004-apache'
    v.vm.network 'private_network',
                 ip: IP_ADDRESSES[v.vm.hostname],
                 libvirt__dhcp_enabled: false
    v.vm.synced_folder '.', '/vagrant', type: 'rsync'
  end
end
