Vagrant.configure('2') do |config|
  # Basic rocky linux 8 box
  config.vm.define 'rockylinux8' do |v|
    v.vm.box = 'rockylinux/8'
    v.vm.hostname = 'rockylinux8'
    v.vm.provision 'shell', path: 'scripts/rhel/rhel_default.sh'
    v.vm.network 'private_network',
                 ip: IP_ADDRESSES[v.vm.hostname],
                 libvirt__dhcp_enabled: false
    v.vm.synced_folder '.', '/vagrant', type: 'rsync'
  end
end
