Vagrant.configure('2') do |config|
  # Basic windows 10 box
  config.vm.define 'windows10' do |v|
    v.vm.box = 'peru/windows-10-enterprise-x64-eval'
    v.vm.hostname = 'windows10'
    v.vm.network 'private_network',
                 ip: IP_ADDRESSES[v.vm.hostname],
                 libvirt__dhcp_enabled: false
    v.vm.synced_folder '.', '/vagrant', type: 'nfs', nfs_version: 3
  end
end
